import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Award,
  BadgeDollarSign,
  Barcode,
  BookOpen,
  Building,
  Building2,
  Calculator,
  CalendarPlus,
  Check,
  CheckCircle2,
  Circle,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleHelp,
  ClipboardList,
  Clock,
  Coins,
  DollarSign,
  FilePlus2,
  FileSignature,
  FileText,
  FileWarning,
  FlaskConical,
  Folder,
  FolderOpen,
  FolderPlus,
  Gavel,
  HandCoins,
  Handshake,
  Home,
  IdCard,
  Inbox,
  Info,
  Landmark,
  type LucideIcon,
  Loader2,
  Mail,
  MailCheck,
  MapPinned,
  MessageCircle,
  Phone,
  PieChart,
  Plus,
  Receipt,
  Scale,
  Search,
  SearchX,
  Send,
  ShieldCheck,
  ShieldUser,
  SlidersHorizontal,
  Store,
  Tag,
  Trash2,
  TriangleAlert,
  Unlink,
  UserCheck,
  UserLock,
  UserPlus,
  Wallet,
  X,
} from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * O catálogo (seed + admin) guarda o ícone como classe Font Awesome legada
 * (ex.: "fas fa-hand-holding-dollar"), herdada do portal antigo do GED. O
 * projeto não carrega mais Font Awesome (sem CDN, sem `<i className>` cru) —
 * este registro resolve a string para um ícone `lucide-react` equivalente.
 * Ícone sem mapeamento cai no genérico (`FileText`), não quebra a tela.
 */
const REGISTRO: Record<string, LucideIcon> = {
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-right-to-bracket": UserCheck,
  "right-from-bracket": UserCheck,
  barcode: Barcode,
  book: BookOpen,
  building: Building,
  "building-circle-exclamation": FileWarning,
  "building-columns": Landmark,
  calculator: Calculator,
  "calendar-plus": CalendarPlus,
  certificate: Award,
  "chart-pie": PieChart,
  check: Check,
  "check-circle": CheckCircle2,
  "circle-check": CheckCircle2,
  circle: Circle,
  "circle-exclamation": AlertCircle,
  "circle-info": Info,
  "circle-question": CircleHelp,
  city: Building2,
  "clipboard-list": ClipboardList,
  clock: Clock,
  coins: Coins,
  "comment-dots": MessageCircle,
  "dollar-sign": DollarSign,
  envelope: Mail,
  "envelope-circle-check": MailCheck,
  "file-alt": FileText,
  "file-circle-plus": FilePlus2,
  "file-contract": FileSignature,
  "file-invoice": FileText,
  "file-invoice-dollar": Receipt,
  "file-lines": FileText,
  "file-pdf": FileText,
  "file-shield": ShieldCheck,
  "file-signature": FileSignature,
  flask: FlaskConical,
  folder: Folder,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  gavel: Gavel,
  "hand-holding-dollar": HandCoins,
  handshake: Handshake,
  home: Home,
  "id-badge": IdCard,
  inbox: Inbox,
  "info-circle": Info,
  landmark: Landmark,
  "link-slash": Unlink,
  list: ClipboardList,
  "magnifying-glass": Search,
  "magnifying-glass-dollar": BadgeDollarSign,
  "map-location-dot": MapPinned,
  "paper-plane": Send,
  pen: FileSignature,
  phone: Phone,
  plus: Plus,
  question: CircleHelp,
  receipt: Receipt,
  "scale-balanced": Scale,
  search: Search,
  "shield-halved": ShieldUser,
  sliders: SlidersHorizontal,
  spinner: Loader2,
  store: Store,
  timeline: ClipboardList,
  trash: Trash2,
  "triangle-exclamation": TriangleAlert,
  "user-check": UserCheck,
  "user-lock": UserLock,
  "user-plus": UserPlus,
  "user-shield": ShieldUser,
  "user-tag": Tag,
  wallet: Wallet,
  xmark: X,
};

/** Extrai o nome do ícone (ex.: "hand-holding-dollar") de uma classe Font Awesome legada. */
function nomeDoIcone(classeFontAwesome: string): string {
  return classeFontAwesome.replace(/^fa[srb]?\s+fa-/, "").trim();
}

interface CatalogoIconProps {
  /** Classe Font Awesome legada guardada no catálogo (ex.: `servico.icone`). */
  nome: string | undefined | null;
  className?: string;
}

/** Resolve o ícone legado do catálogo (JSONB) para um componente `lucide-react`. */
export function CatalogoIcon({ nome, className }: CatalogoIconProps) {
  const Icone = (nome && REGISTRO[nomeDoIcone(nome)]) || FileText;
  return <Icone className={cn("size-5", className)} aria-hidden="true" />;
}

export { ChevronDown, ChevronRight, ChevronUp, SearchX };
